fixes

diff --git a/helper/az-login-as-sp b/helper/az-login-as-sp
--- a/helper/az-login-as-sp
+++ b/helper/az-login-as-sp
@@ -36,14 +36,14 @@ fi
 # Does the passed in file exist
 if ! [ -f $AUTH_FILE ]; then
     echo "File not found!" >&2
-    return 1
+    exit 1
 fi
 
 # Determine if this is really a JSON file
-jq -e . >/dev/null 2>&1 <<< cat $1; rc=$?
+jq -e . >/dev/null 2>&1 <<< cat $AUTH_FILE; rc=$?
 if [[ $rc != 0 ]]; then
-    echo "Must be an Azure Auth file in JSON format"
-    return 1
+    echo "ERROR:  Must be an Azure Auth file in JSON format"
+    exit 1
 fi
 JSON=$AUTH_FILE
 
@@ -52,18 +52,7 @@ currentCloud=$(az cloud show -o json | jq -er 'select(.name != null) | .name')
 
 if [ -z $currentCloud ]; then
     echo "Must be signed into Azure.  Please login"
-    return 1
-fi
-
-if [ "$currentCloud" = "$AZURE_GOV_CLOUD" ]; then
-    cloud="USGovernment"
-    location="usgovvirginia"
-elif [ "$currentCloud" = "$AZURE_PUB_CLOUD" ]; then
-    cloud="Public"
-    location="East US"
-else
-    echo "Current cloud not supported via this script"
-    return 1
+    exit 1
 fi
 
 # Parse the file looking for some stuff
@@ -74,28 +63,28 @@ secretKey=$(cat $JSON | jq -e -r 'select(.clientSecret != null) | .clientSecret'
 endpoint=$(cat $JSON | jq -e -r 'select(.activeDirectoryEndpointUrl != null) | .activeDirectoryEndpointUrl')
 
 # Check to see if the auth file is for Gov
-if [[ $endpoint =~ "\.us$" ]]; then
+if [[ $endpoint =~ us$ ]]; then
     # Exit if in the wrong cloud
-    if [ "$currentCloud" != $AZURE_GOV_CLOUD ]; then
+    if [ "$currentCloud" != "AzureUSGovernment" ]; then
         echo "You are logged into the wrong cloud to use this authorization file"
-        return 1
+        exit 1
     fi
-elif [[ $endpoint =~ "\.com$" ]]; then
+elif [[ $endpoint =~ com$ ]]; then
     # Exit if in the wrong cloud
-    if [ "$currentCloud" != $AZURE_PUB_CLOUD ]; then
+    if [ "$currentCloud" != "AzureCloud" ]; then
         echo "You are logged into the wrong cloud to use this authorization file"
-        return 1
+        exit 1
     fi
 else
     echo "Unsupported cloud in auth file. Exiting."
-    return 1
+    exit 1
 fi
 
 
 if [ -z $clientId ]  || [ -z $subscriptionId ] || [ -z $tenantId ] || [ -z $secretKey ] ; then
     echo "File does not contain one or more of the following:"
     echo "clientId, subscriptionId, tenantId and/or clientSecret"
-    return 1
+    exit 1
 fi
 
 #echo "clientId=$clientId"
