added aks create check

diff --git a/iaas/az-k8s b/iaas/az-k8s
--- a/iaas/az-k8s
+++ b/iaas/az-k8s
@@ -198,6 +198,9 @@ createAKSCluster() {
     fi
     cmd="az aks create -g $RG -n $NAME $SCALE -l $REGION $SSH_KEY_SECTION --kubernetes-version $VERSION"
     eval $cmd
+    if [ $? -ne 0 ]; then
+        echo "ERROR:  aks create command failed.  Check stderr"
+    fi
 
     K8S_RG=$( az resource show -n $NAME -g $RG -o tsv --resource-type Microsoft.ContainerService/managedClusters --query properties.nodeResourceGroup )
 
